# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Spark

# Short description (goes below the title; it will also be used in the RSS feed)
description: "Dedicated to the making of things"

# Longer description for title page
title_description: "A place to put project descriptions, tutorials, and some of the things I learned along the way."
#title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/becomesaflame/becomesaflame.github.io
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Your name, as you want it to appear underneath each post and in the footer
author: Spark

# Your email if you want it to be linked on the contact page
author_email: spark.scul+blog@gmail.com

# Produce an index for related posts
lsi: false

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://becomesaflame.github.io

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

#### Under the Hood Stuff #####

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
#paginate: 3

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
